ALTER TABLE "Application"
ALTER COLUMN "status" SET DEFAULT 'PENDING_APPROVAL';

UPDATE "Application"
SET "status" = 'PENDING_APPROVAL'
WHERE "status" IN ('SUBMITTED_PENDING_APPROVAL', 'SUBMITTED');

UPDATE "Application"
SET "status" = 'APPROVED_FOR_CHAPTER_ADJUDICATION'
WHERE "status" IN ('CHAPTER_ADJUDICATION', 'CHAPTER_REVIEW');

UPDATE "Application"
SET "status" = 'PENDING_NATIONAL_ACCEPTANCE'
WHERE "status" = 'CHAPTER_APPROVED';

UPDATE "Application"
SET "status" = 'APPROVED_FOR_NATIONAL_ADJUDICATION'
WHERE "status" IN ('NATIONAL_FINALS', 'NATIONAL_REVIEW');

UPDATE "Application"
SET "status" = 'EXCLUDED'
WHERE "status" IN ('CHAPTER_REJECTED', 'NATIONAL_REJECTED');

UPDATE "Application"
SET "status" = 'WITHDRAWN'
WHERE "status" IN ('NATIONAL_APPROVED', 'DECIDED');
