-- AlterEnum
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED_PENDING_APPROVAL';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CHAPTER_ADJUDICATION';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'NATIONAL_FINALS';
