ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CORRECTION_REQUIRED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'APPROVED_FOR_CHAPTER_ADJUDICATION';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'PENDING_NATIONAL_ACCEPTANCE';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'APPROVED_FOR_NATIONAL_ADJUDICATION';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'EXCLUDED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'ALTERNATE';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';
